# Generated by Django 4.2.7 on 2023-12-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karDetail', '0002_remove_car_user_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='karDetail/media/car_images/'),
        ),
    ]
