# Generated by Django 4.2.7 on 2023-12-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karDetail', '0005_remove_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='karDetail/media/uploads/'),
        ),
    ]
