# Generated by Django 4.2.7 on 2023-12-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karBrand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
